meta:
  schema-version: 0.1.0
  created-on: "2025-05-18T16:47:09Z"
  cli-version: v0.3.165
projects:
  88BF3FA92E42EDA428C875F5A7FA22E2DEAC9168:
    targets:
      - requirements.txt
    manager:
      ecosystem: python
      name: pip
      version: 24.3.1
      class: manifest
    overrides:
      setuptools:
        58.1.0:
          use: 58.1.0+sp2
