name: Seal Local Fix (Python Audit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  seal-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display project structure
      run: ls -la

    - name: Show requirements.txt content
      run: cat requirements.txt

    - name: Download and run Seal CLI (local mode)
      run: |
        curl -sSfL https://github.com/seal-community/cli/releases/download/latest/seal-linux-amd64-latest -o seal
        chmod +x seal
        ./seal fix . --mode local
