name: Seal + Xray Docker Scan

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  JFROG_CLI_BUILD_NAME: seal-docker-security
  JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
  JF_URL: ${{ secrets.JF_URL }}

jobs:
  docker-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI with Username and Token
        run: |
          jf config add my-server \
            --url=${{ secrets.JF_URL }} \
            --user=${{ secrets.JFROG_USER }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false
          jf config use my-server

      - name: Build Docker Image
        run: |
          echo "🐳 Building Docker image..."
          docker build -t cpart.jfrog.io/seal-docker-demo/seal-poc:${{ github.run_number }} .

      - name: Scan Docker Image with Xray (Local)
        run: |
          echo "🔍 Running Docker scan with Xray..."
          jf docker scan cpart.jfrog.io/seal-docker-demo/seal-poc:${{ github.run_number }} \
            --licenses --format=json --vuln --project seal-scan \
            --build-name=${{ env.JFROG_CLI_BUILD_NAME }} \
            --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --server-id=my-server || echo "🟡 Warnings found"

      - name: Push Docker Image to Artifactory
        run: |
          echo "📦 Pushing Docker image to Artifactory..."
          jf rt docker-push cpart.jfrog.io/seal-docker-demo/seal-poc:${{ github.run_number }} seal-docker-demo \
            --build-name=${{ env.JFROG_CLI_BUILD_NAME }} \
            --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --server-id=my-server

      - name: Publish Build Info
        run: |
          echo "🚀 Publishing build info to Artifactory..."
          jf rt build-publish ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --server-id=my-server

      - name: Trigger Xray Build Scan
        run: |
          echo "🛡️ Scanning build with Xray..."
          jf build-scan ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }} \
            --server-id=my-server
