name: Seal Fix Dry Run (Python)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  seal-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and run Seal fix (dry run)
      run: |
        curl -sSfL https://github.com/seal-community/cli/releases/download/latest/seal-linux-amd64-latest -o seal
        chmod +x seal
        ls -la
        cat requirements.txt
        ./seal fix --dry-run --file requirements.txt
