name: Seal Audit (No Signup)

on:
  push:
    branches: [ main ]

jobs:
  seal-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and run Seal CLI (audit only)
      run: |
        curl -sSfL https://github.com/seal-community/cli/releases/download/latest/seal-linux-amd64-latest -o seal
        chmod +x seal
        ./seal audit -r requirements.txt
