name: Seal Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  seal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pipx and Seal CLI
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx ensurepath
        pipx install seal-seal

    - name: Run Seal patch
      run: ~/.local/bin/seal patch -r requirements.txt -o patched_requirements.txt

    - name: Show patched file
      run: cat patched_requirements.txt
